### ISSUE TITLE
Filesystem List Hangs

### ISSUE THREAD

**Issue by dthain** [NunyaOS/Nunya#52]
Boot Nunya, and then attempt to list any directory:

```
git clone https://github.com/NunyaOS/Nunya
cd src
make
qemu-system-i386 --cdrom basekernel.iso

ls /
ata: timeout
(hang)

ls /2
ata: timeout
(hang)

ls /3 
ata: timeout
(hang)
```

**Comment by rboccabe** [comment]
This was on our scaffolding command line from the console. The ls simply assumed that there was a .iso image at the secondary slave position, and was treating the root of that iso 9660 file system as the root of the entire file system for the computer.

Once we package ls in with a /usr/bin of some sort, this problem will eliminate itself as no one will have access to the console's version of ls, so provided that the dev's working now, who are using the console as a dev tool only, know that an ls at the console will get you a listing of an iso on ata unit 3, it might not be worth it to correct this version of ls.
