### ISSUE TITLE
Crash on Bootup in Virtualbox

### ISSUE THREAD

**Issue by kkoser** [NunyaOS/Nunya#74]
The OS can crash on boot up in Virtualbox with a "Guru Error". This error appears to become more frequent as the amount of kernel code increases. This can be tested by adding extra code such as print statements anywhere in the kernel. 

After investigation, we believe this may be due to a corruption of the interrupt table by kernel code.

**Comment by Shashwatsh** [comment]
add files.iso too

**Comment by kkoser** [comment]
After investigation, this is caused by the large mouse_draw_buffer static allocation in mouse.h. This buffer is used to store previous screen state before mouse overdraw, and is larger than a single page and therefore cannot be kmalloc'd

**Comment by kkoser** [comment]
Fixed by giving mouse draw buffer two direct pages in memory. Should revisit this later when allocations are more well-rounded

**Comment by dthain** [comment]
Nice catch!
